### ISSUE TITLE
Simple classes do not work

### ISSUE THREAD

**Issue by AlexeyPavlyuck** [meluiz/tailant#10]
Simple classes without brackets do not work.
For example, if hover:text-xl does't work, hover:(text-xl) is already working
It also does not work with and without function css () - in usual tailwind format

**Comment by AlexeyPavlyuck** [comment]
<img width="263" alt="Снимок экрана 2023-07-12 в 12 23 52" src="https://github.com/meluiz/tailant/assets/63820958/62b139f6-c410-467a-826e-17d25cf42ff7">
does't work in all class cases of div

<img width="263" alt="Снимок экрана 2023-07-12 в 12 26 18" src="https://github.com/meluiz/tailant/assets/63820958/9a864590-6b67-47bb-ace0-7bd37e31f064">
But if you write this way, both the upper and lower div class work

**Comment by meluiz** [comment]
@AlexeyPavlyuck 
It is a problem with the transformer. Sorry for uploading a new version with this issue. It will be fixed soon!

**Comment by meluiz** [comment]
Can you provide me with the version of your Tailwind, please? I ran some tests now, and it's working fine.

**Comment by AlexeyPavlyuck** [comment]
Yes, version 3.3.1

**Comment by meluiz** [comment]
The fix has been applied in version 1.1.2. If you can update and provide feedback, I would appreciate it.
