### ISSUE TITLE
Condition in custom variant

### ISSUE THREAD

**Issue by AlexeyPavlyuck** [meluiz/tailant#13]
Hi! It's me again.)

The problem here is in conditions like this, styles don't work:
<img width="761" alt="Снимок экрана 2023-08-09 в 11 15 25" src="https://github.com/meluiz/tailant/assets/63820958/a964e59e-eab1-4361-bee8-0a720ef2d478">

**Comment by meluiz** [comment]
@AlexeyPavlyuck I have a lot of tasks and little time. I haven't forgotten about your issue. This bug will be reevaluated and fixed as soon as possible.

**Comment by meluiz** [comment]
First of all, I want to apologize for the delay in reviewing the issue.

This problem occurs due to the incorrect way the element was styled. To work as expected, without deviating from the tailant's proposal, you should use something like:

```tsx
<div className={css(true ? '[&>.test-div]:(text-slate-blue-500)' : '[&>.test-div]:(text-neutral-300)')}>
  <div className="test-div">TEST</div>
</div>
```
