### ISSUE TITLE
Support custom variant

### ISSUE THREAD

**Issue by AlexeyPavlyuck** [meluiz/tailant#8]
Hey!  
Please add support custom variant like [&.class]:(mt-10 mb-20)

**Comment by AlexeyPavlyuck** [comment]
<img width="196" alt="Снимок экрана 2023-07-07 в 19 24 04" src="https://github.com/meluiz/tailant/assets/63820958/77bdb421-7f0d-4a97-8d8d-e2e89258983a">

And custom variant breakpoint doesn't work too, fix please)

Your work is cool, thank you very much!

**Comment by meluiz** [comment]
@AlexeyPavlyuck

I am aware of some issues like these. The current regex also cannot recognize functions within Tailwind variant groups. As soon as I have some free time, I will rewrite the way classes are processed, providing support for these minor issues.

Thank you for opening the issue, it is being investigated.

**Comment by meluiz** [comment]
@AlexeyPavlyuck A new version has been released and promises to fix the mentioned issues. Version 1.1.0 introduced a new way of handling variant group identification and generating classes for them.

**Comment by AlexeyPavlyuck** [comment]
Awesome. Custom variants is works now. Thanks!
